# Generated by Django 2.1.5 on 2020-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Joe', max_length=20, unique=True),
        ),
    ]
