# Generated by Django 2.2.4 on 2020-03-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glover', '0005_auto_20200306_1715'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_likes',
        ),
    ]
