# Generated by Django 2.2.4 on 2020-03-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glover', '0006_auto_20200306_1717'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('profile', 'profile_liked'), name='unique_likes'),
        ),
    ]
