# Generated by Django 2.2.4 on 2020-03-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glover', '0007_auto_20200306_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='glover.Profile'),
        ),
        migrations.AlterField(
            model_name='like',
            name='profile_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='glover.Profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='profile1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='glover.Profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='profile2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched', to='glover.Profile'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('profile1', 'profile2'), name='unique_matches'),
        ),
    ]
