# Generated by Django 3.0.4 on 2020-03-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glover', '0010_auto_20200320_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_content',
            new_name='message',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glover.Profile')),
            ],
        ),
    ]
