# Generated by Django 3.0.4 on 2020-03-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glover', '0011_auto_20200331_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
